import React,{useMemo,useState} from 'react'; import {createRoot} from 'react-dom/client';
import {Activity,ArrowRight,Check,ChevronDown,Cloud,Download,Eye,FileText,Focus,ImagePlus,Layers3,Lock,Menu,Play,Search,ShieldCheck,Sparkles,Split,Upload,Video, X,ZoomIn} from 'lucide-react';
import {demoAssets,elements} from './data/demo'; import {cloudinaryStatus} from './lib/cloudinary'; import './styles.css';

const status=cloudinaryStatus();
function App(){
 const [asset,setAsset]=useState(demoAssets[0]); const [selected,setSelected]=useState('waste'); const [tab,setTab]=useState('workspace'); const [transform,setTransform]=useState(null); const [notice,setNotice]=useState(''); const [query,setQuery]=useState(''); const [aiAnalysis,setAiAnalysis]=useState(null);
 const detectedElements=aiAnalysis?.observations?.map((item,index)=>({id:`ai-${index}-${item.label}`,label:item.label.replace(/\b\w/g,c=>c.toUpperCase()),color:['#e9a85c','#67c3c8','#91b86c','#cf8aa9','#b4a1de'][index%5],confidence:Math.round(item.confidence*100),category:item.category,region:{left:item.region.left*100,top:item.region.top*100,width:item.region.width*100,height:item.region.height*100},observation:item.observation,interpretation:item.interpretation,count:'AI estimate'}))||elements;
 const active=detectedElements.find(e=>e.id===selected)||detectedElements[0]; const results=useMemo(()=>query?demoAssets.filter(a=>(a.elements.join(' ')+a.name+a.location).toLowerCase().includes(query.toLowerCase())):demoAssets,[query]);
 const act=(message,fn)=>{setNotice(message); if(fn)fn(); setTimeout(()=>setNotice(''),3500)};
 const analyzeWithAI=async()=>{try{const api=import.meta.env.VITE_API_URL||'http://127.0.0.1:8787';const response=await fetch(`${api}/api/analysis`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({assetId:asset.id,secureUrl:asset.image,publicId:asset.source})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Analysis failed');setAiAnalysis(result);setSelected(`ai-0-${result.observations?.[0]?.label||""}`);act(result.status==='AI_ANALYSIS'?'AI vision analysis complete — labels refreshed.':'Demo fallback returned — check API status.')}catch(error){act(error.message)}};
 return <div className="app"><aside className="sidebar"><div className="brand"><div className="brandmark">✦</div><div><b>impact<span>lens</span></b><small>VISUAL EVIDENCE</small></div></div><div className="workspace-switch"><span className="dot green"/>Lake Restoration <ChevronDown size={14}/></div><nav><Nav icon={<Focus/>} text="Element workspace" active={tab==='workspace'} onClick={()=>setTab('workspace')}/><Nav icon={<ImagePlus/>} text="Evidence library" active={tab==='library'} onClick={()=>setTab('library')}/><Nav icon={<Split/>} text="Comparisons" active={tab==='compare'} onClick={()=>setTab('compare')}/><Nav icon={<FileText/>} text="Reports" active={tab==='reports'} onClick={()=>setTab('reports')}/></nav><div className="nav-label">PROJECT SIGNALS</div><div className="signal"><span className="signal-dot amber"/><div><b>Shoreline cleanup</b><small>12 assets · 4 pairs</small></div></div><div className="signal"><span className="signal-dot teal"/><div><b>School water access</b><small>8 assets · 2 pairs</small></div></div><div className="sidebar-bottom"><div className="mode"><span className="dot amber"/><div><b>Demo mode</b><small>Using recorded fixtures</small></div></div><div className="profile"><div className="avatar">AK</div><div><b>Arjun Kumar</b><small>Field researcher</small></div><ChevronDown size={14}/></div></div></aside>
 <main className="main"><header><div className="crumb">LAKE RESTORATION <span>/</span> {tab==='workspace'?'ELEMENT WORKSPACE':tab.toUpperCase()}</div><div className="header-actions"><div className="cloud-state"><span className="dot amber"/> {status.mode==='demo'?'DEMO MODE':'CLOUDINARY CONNECTED'}</div><button className="icon-btn"><Activity size={17}/></button><button className="avatar small">AK</button></div></header>
 {notice&&<div className="toast"><Check size={16}/>{notice}</div>}
 {tab==='workspace'&&<section style={{padding:'20px 48px'}}><button className="upload-btn" onClick={analyzeWithAI}><Sparkles size={16}/> Analyze current image with OpenAI</button>{aiAnalysis&&<div><h2>Live analysis · {aiAnalysis.model}</h2><p>Approximate regions and confidence are model estimates.</p>{aiAnalysis.observations.map((item,index)=><article key={index}><h3>{item.label}</h3><p>Observation: {item.observation}</p><p>Interpretation: {item.interpretation}</p></article>)}</div>}</section>}
 {tab==='workspace'?<Workspace asset={asset} active={active} detectedElements={detectedElements} selected={selected} setSelected={setSelected} transform={transform} setTransform={setTransform} act={act} analyzeWithAI={analyzeWithAI} aiAnalysis={aiAnalysis}/>:<Library tab={tab} results={results} query={query} setQuery={setQuery} setAsset={setAsset} setTab={setTab} act={act}/>}</main></div>
}
function Nav({icon,text,active,onClick}){return <button className={'nav-item '+(active?'active':'')} onClick={onClick}>{React.cloneElement(icon,{size:18})}<span>{text}</span>{active&&<span className="nav-line"/>}</button>}
function Workspace({asset,active,detectedElements,selected,setSelected,transform,setTransform,act}){return <div className="workspace"><section className="hero-copy"><div><div className="eyebrow"><span className="live-dot"/> ANALYSIS COMPLETE <span className="divider"/> ASSET {asset.id}</div><h1>See what’s really<br/><em>in the frame.</em></h1><p>ImpactLens turns visual evidence into understood, traceable elements.<br/>Select a signal to inspect it, transform it, or compare it.</p></div><button className="upload-btn" onClick={()=>act('Upload handoff ready — connect Cloudinary to add an original asset.') }><Upload size={16}/> Upload evidence <span>⌘U</span></button></section><section className="canvas-grid"><div className="image-panel"><div className="image-toolbar"><div><span className="pill original">ORIGINAL</span><span className="asset-name">{asset.name}</span></div><div className="toolbar-right"><span className="mini-label"><Lock size={12}/> IMMUTABLE SOURCE</span><button className="icon-btn dark"><ZoomIn size={16}/></button><button className="icon-btn dark"><Menu size={16}/></button></div></div><div className="media-wrap"><img src={asset.image} alt="Illustrative shoreline evidence"/><div className="image-shade"/>{detectedElements.map(e=><button key={e.id} aria-label={'Select '+e.label} className={'region '+(selected===e.id?'selected':'')} style={{left:e.region.left+'%',top:e.region.top+'%',width:e.region.width+'%',height:e.region.height+'%',borderColor:e.color, '--region':e.color}} onClick={()=>setSelected(e.id)}><span style={{background:e.color}}>{e.label.toUpperCase()}</span></button>)}</div><div className="image-footer"><span><Eye size={14}/> {detectedElements.length} elements detected</span><span><span className="dot green"/> Analysis v1.2 · 14 Jun 2026</span></div></div><ElementPanel detectedElements={detectedElements} active={active} selected={selected} setSelected={setSelected} transform={transform} setTransform={setTransform} act={act}/></section><EvidenceStrip asset={asset} act={act}/></div>}
function ElementPanel({detectedElements,active,selected,setSelected,transform,setTransform,act}){return <aside className="element-panel"><div className="panel-heading"><div><div className="eyebrow">DETECTED ELEMENTS <span className="count">{detectedElements.length}</span></div><h2>What’s in this image?</h2></div><button className="more">•••</button></div><div className="element-list">{detectedElements.map(e=><button className={'element-row '+(selected===e.id?'chosen':'')} key={e.id} onClick={()=>setSelected(e.id)}><span className="element-icon" style={{background:e.color+'20',color:e.color}}>{e.label[0]}</span><span className="element-info"><b>{e.label}</b><small>{e.category}</small></span><span className="confidence">{e.confidence}%</span><span className="chev">›</span></button>)}</div><div className="insight"><div className="insight-head"><span className="spark">✦</span><div><div className="eyebrow">SELECTED SIGNAL</div><h3>{active.label}</h3></div><span className="confidence-badge">{active.confidence}%</span></div><div className="facts"><div><small>OBSERVATION</small><p>{active.observation}</p></div><div className="interpret"><small>INTERPRETATION</small><p>{active.interpretation}</p></div></div><div className="location"><span style={{background:active.color}}/> REGION · {active.count} · approx. location</div></div><div className="actions"><button onClick={()=>act('Focus derivative prepared from the selected region.',()=>setTransform('focus'))}><Focus size={15}/> Focus</button><button onClick={()=>act('Comparison view queued for this element.',()=>setTransform('compare'))}><Split size={15}/> Compare</button><button onClick={()=>act('Element isolate preview prepared.',()=>setTransform('isolate'))}><Layers3 size={15}/> Isolate</button><button onClick={()=>act('Transform controls opened.',()=>setTransform('shift'))} className="primary"><Sparkles size={15}/> Transform</button></div>{transform&&<TransformCard type={transform} active={active} act={act}/>}</aside>}
function TransformCard({type,active,act}){let label={focus:'Focus / reframe',compare:'Element comparison',isolate:'Isolate element',shift:'Shift element'}[type];return <div className="transform-card"><div className="eyebrow"><Sparkles size={13}/> DERIVATIVE PREVIEW</div><b>{label}</b><p>{type==='shift'?'Cloudinary transformation boundary ready. The original remains untouched.':'A non-destructive Cloudinary derivative will be generated from this region.'}</p><div className="transform-meta"><span><span className="dot amber"/> AI / TRANSFORMED DERIVATIVE</span><span>Source retained</span></div><button onClick={()=>act(label+' derivative generated in demo mode.')}>Generate derivative <ArrowRight size={14}/></button></div>}
function EvidenceStrip({asset,act}){return <section className="evidence-strip"><div className="strip-title"><div><div className="eyebrow">EVIDENCE CHAIN</div><h2>From capture to claim</h2></div><button className="text-btn" onClick={()=>act('Provenance verified · chain intact.') }><ShieldCheck size={15}/> Verify provenance</button></div><div className="chain"><ChainStep icon={<ImagePlus/>} label="ORIGINAL" detail={asset.id} active/><div className="chain-line"/><ChainStep icon={<Eye/>} label="ANALYSIS" detail="5 elements · v1.2"/><div className="chain-line"/><ChainStep icon={<Sparkles/>} label="TRANSFORMATION" detail="Awaiting action"/><div className="chain-line"/><ChainStep icon={<Check/>} label="DERIVATIVE" detail="Not generated" muted/></div></section>}
function ChainStep({icon,label,detail,active,muted}){return <div className={'chain-step '+(active?'active ':'')+(muted?'muted':'')}><div className="chain-icon">{React.cloneElement(icon,{size:16})}</div><div><small>{label}</small><b>{detail}</b></div></div>}
function Library({tab,results,query,setQuery,setAsset,setTab,act}){return <div className="library"><div className="library-title"><div><div className="eyebrow">{tab==='library'?'EVIDENCE LIBRARY':tab==='compare'?'CHANGE INTELLIGENCE':'EVIDENCE REPORTS'}</div><h1>{tab==='library'?'Find the signal.':'Make every claim traceable.'}</h1><p>{tab==='library'?'Search across detected elements, projects, and visual evidence.':'Verified evidence is ready to turn into a defensible story.'}</p></div><button className="upload-btn" onClick={()=>act('Upload handoff ready — connect Cloudinary to add an original asset.') }><Upload size={16}/> Upload evidence</button></div>{tab==='library'&&<div className="search-box"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search elements, places, or activities…"/><span>⌘ K</span></div>}<div className="results-head"><span>{tab==='library'?results.length+' assets · semantic index ready':'3 verified evidence objects'}</span><button className="filter">Most relevant <ChevronDown size={14}/></button></div><div className="asset-grid">{results.map(a=><button className="asset-card" key={a.id} onClick={()=>{setAsset(a);setTab('workspace')}}><div className="asset-thumb"><img src={a.image} alt=""/><span className="pill">{a.tag}</span><span className="match"><Check size={12}/> {a.confidence}% understood</span></div><div className="asset-card-body"><div><b>{a.name}</b><small>{a.location} · {a.date}</small></div><ArrowRight size={16}/><div className="asset-tags">{a.elements.map(e=><span key={e}>{e}</span>)}</div></div></button>)}</div>{tab==='reports'&&<div className="report-callout"><FileText size={24}/><div><b>Lake Restoration — Evidence-backed impact report</b><p>12 claims linked to 28 original assets · last verified today</p></div><button onClick={()=>act('Report export prepared in demo mode.')}><Download size={15}/> Export pack</button></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
